# Generated by Django 3.2.9 on 2022-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Expirydate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MfgDate',
            field=models.CharField(max_length=20),
        ),
    ]
